---
- name: OpenStack | create user
  openstack.cloud.identity_user:
    cloud: pbos
    name: "{{ os_service_name }}"
    password: "{{ os_password }}"
    domain: default
    default_project: service
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true
  no_log: true

- name: OpenStack | add admin role to user
  openstack.cloud.role_assignment:
    cloud: pbos
    user: "{{ os_service_name }}"
    role: admin
    project: service
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true

- name: OpenStack | create service
  openstack.cloud.catalog_service:
    cloud: pbos
    name: "{{ item.name }}"
    service_type: "{{ item.type }}"
    description: OpenStack Orchestration Service
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true
  loop:
    - {name: "{{ os_service_name }}", type: "container-infra"}

- name: OpenStack | create endpoints for service
  openstack.cloud.endpoint:
    cloud: pbos
    service: "{{ os_service_name }}"
    endpoint_interface: "{{ item }}"
    url: "http://{{ keepalived_vip }}:{{ magnum_port }}/v1"
    region: RegionOne
    state: present
  loop: "{{ os_endpoint_interface }}"
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true

- name: OpenStack | create magnum domain
  openstack.cloud.identity_domain:
    cloud: pbos
    name: magnum
    description: "Owns users and projects created by magnum"
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true

- name: OpenStack | create magnum domain admin user to manage magnum domain
  openstack.cloud.identity_user:
    cloud: pbos
    name: "magnum_domain_admin"
    password: "{{ os_password }}"
    domain: magnum
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true
  no_log: true

- name: OpenStack | add admin role to magnum domain admin user
  openstack.cloud.role_assignment:
    cloud: pbos
    user: "magnum_domain_admin"
    role: admin
    domain: magnum
    state: present
  delegate_to: "{{ groups['keystone'][0] }}"
  run_once: true
...
